quick_quote_post_location_threshold:
  type: integer
  default: 0
  description:
    en: "Number of posts back before fast quote enabled."
    zh_CN: "距离最新帖子多少层以内时，快速引用功能将被禁用（设为 0 表示始终启用）。"
quick_quote_save_link_text:
  type: bool
  default: true
  description:
    en: "Keep link text. If disabled, the link will be completely removed."
    zh_CN: "保留链接文字。若禁用，链接将完全移除"
quick_quote_remove_contiguous_new_lines:
  type: bool
  default: true
  description:
    en: "Remove unnecessary new lines"
    zh_CN: "移除多余的连续空行"
quick_quote_character_limit:
  type: integer
  default: 50
  description:
    en: "Quote character limit (uses first x chars if total length is greater)"
    zh_CN: "引用内容字符数限制（超过使用开头的 x 个字符）"
